services:
  postgres:
    image: postgres:16-alpine
    container_name: rms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rms
    ports:
      - "5432:5432"
    volumes:
      - rms-postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: rms-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rms
    ports:
      - "27017:27017"
    volumes:
      - rms-mongo:/data/db

  redis:
    image: redis:7-alpine
    container_name: rms-redis
    ports:
      - "6379:6379"
    volumes:
      - rms-redis:/data

volumes:
  rms-postgres:
  rms-mongo:
  rms-redis:
