export const PERMISSIONS = {
  SUPER_ADMIN_ALL: "super_admin:*",

  TENANT_READ: "tenant:read",
  TENANT_WRITE: "tenant:write",

  BRANCH_READ: "branch:read",
  BRANCH_WRITE: "branch:write",

  USER_READ: "user:read",
  USER_WRITE: "user:write",

  MENU_READ: "menu:read",
  MENU_WRITE: "menu:write",

  INVENTORY_READ: "inventory:read",
  INVENTORY_WRITE: "inventory:write",

  ORDER_READ: "order:read",
  ORDER_WRITE: "order:write",

  KDS_READ: "kds:read",
  KDS_WRITE: "kds:write",

  PAYMENT_READ: "payment:read",
  PAYMENT_WRITE: "payment:write",

  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export"
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS = {
  SUPER_ADMIN: [PERMISSIONS.SUPER_ADMIN_ALL],
  ORG_ADMIN: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_WRITE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_WRITE,
    PERMISSIONS.KDS_READ,
    PERMISSIONS.KDS_WRITE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_WRITE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT
  ],
  MANAGER: [
    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.MENU_READ,
    PERMISSIONS.MENU_WRITE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.KDS_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.REPORT_READ
  ],
  CASHIER: [
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_WRITE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_WRITE,
    PERMISSIONS.MENU_READ
  ],
  CHEF: [PERMISSIONS.KDS_READ, PERMISSIONS.KDS_WRITE, PERMISSIONS.ORDER_READ],
  WAITER: [PERMISSIONS.ORDER_READ, PERMISSIONS.ORDER_WRITE, PERMISSIONS.MENU_READ]
} as const;

export type RoleKey = keyof typeof DEFAULT_ROLE_PERMISSIONS;
